### ISSUE TITLE
[model support] Requesting support for Gemma 2

### ISSUE THREAD

**Issue by sand-bit** [kvcache-ai/ktransformers#10]
Requesting support for Gemma 2 27B/9B.

1. Sliding window attention, used every other layer
2. Logit soft capping (aka soft capping, so no flash attention support right now)
3. Possible tokenizer bugs in transformer implementation https://github.com/ggerganov/llama.cpp/issues/8240#issuecomment-2212494531 (See that issue for other discussions on tokenizer bugs. Maybe okay in Google's official Keras implementation?)

**Comment by james0zan** [comment]
As it is a dense model, we may currently not be able to run Gemma 2 faster than its official support. Thus, Gemma's support may not be available in the coming days.
