### ISSUE TITLE
How to infer quantized models on CPU&GPU

### ISSUE THREAD

**Issue by shuzhang-pku** [kvcache-ai/ktransformers#103]
I found that ktransformers first performs a dequantize operation when loading the weights. Due to DRAM limitations, I want to directly infer the model with quantized weights on CPU&GPU. How can I implement this?

**Comment by Azure-Tang** [comment]
The dequantised weight will be quantised again into marlin format to use marlin op (which is fast). So if you are using optimising rules that we provided, you are directly using quantized weights.
