### ISSUE TITLE
Is Flash Attention 2 Necessary for Qwen2Moe?

### ISSUE THREAD

**Issue by cherrymorning** [kvcache-ai/ktransformers#11]
I tried to run Qwen2Moe but I only have access to T4 GPUs, which don't support Flash Attention 2.
Is Flash Attention 2 a strict requirement for Qwen2Moe?
Any guidance would be greatly appreciated!

**Comment by Atream** [comment]
Flash Attention 2 is required for Qwen2_moe, or it may overflow. This is Qwen2_moe's own character.
