### ISSUE TITLE
About 1M ctx models

### ISSUE THREAD

**Issue by choyakawa** [kvcache-ai/ktransformers#13]
I saw elsewhere that you mentioned optimization for 1M ctx models (glm-4-9b-chat-1m/internlm2_5-7b-chat-1m) is on the roadmap and will be released in a future version. And I'm interested to know what kind of improvements you're anticipating achieving.

**Comment by james0zan** [comment]
We intend to take advantage from the sparsity of attention operator. There are many great work study on this topic and we are evaluating and integrating some of them into the KTransformers framework.
