### ISSUE TITLE
q5_k_m is not supported?

### ISSUE THREAD

**Issue by keyonzeng** [kvcache-ai/ktransformers#16]
I have checked custom_gguf.py and find that q5_k_m is not supported because function dequantize_q5_k_gpu does nothing.

<img width="225" alt="image" src="https://github.com/user-attachments/assets/eb1ee5cc-ca50-4662-9f02-d29b9ad37c49">

so what is the problem with supporting q5_k_m model?

**Comment by Azure-Tang** [comment]
Yes, we have supported all cpu dequant, but q5km's gpu dequant is on the way, only Q4km and Q8_0 are supported now. If you really need q5k I can open cpu dequant for you, but it will be 10x times slower when you loading your model.

**Comment by BITcyman** [comment]
So sorry to let you wait so long. We have supported  q5_k dequant on gpu now. Other dequant types (q2_k and q3_k) on gpu have been supported as well. You can find more details in ktransformers/utils/custom_gguf.py and ktransformers/ktransformers_ext/cuda/custom_gguf/dequant.cu.

**Comment by 344303947** [comment]
求助：q5_k_m 运行除了模型443GB 还需要多少额外的内存，512GB能起来？
