### ISSUE TITLE
Native windows support

### ISSUE THREAD

**Issue by DotNetDevlll** [kvcache-ai/ktransformers#4]
First of all thanks for your AI community contribution, it's a huge leap forward to use MoE models for consumer grade users with limited VRAM.
Would it be possible to add native Windows support to KTransformers? I'd love to see the project become accessible to windows users as well.

Thanks!

**Comment by azywait** [comment]
> it be possible to add native Windows support to KTransformers? I'd love to see the project become accessible to windows users as well.
> 
> Thanks!

Thanks for your interest. Native Windows support is in our plans, but it may take some time.  😊

**Comment by whisper-bye** [comment]
Has anyone tried to run it under windows?

**Comment by Atream** [comment]
You can try to install from source by running install.bat. Pre-built wheels will be released soon.

**Comment by UnicornChan** [comment]
There might be a few possibilities here.

1. CUDA is not installed on your machine.
2. The CUDA environment variables are not active.
3. The installed PyTorch is not for GPU, but for CPU.

There is a simple env check code
```python
import torch
import subprocess
from torch.utils.cpp_extension import CUDA_HOME
print("torch version is: " + str(torch.__version__))
print("CUDA HOME is: " + str(CUDA_HOME))
raw_output = subprocess.check_output([str(CUDA_HOME) + "/bin/nvcc", "-V"], universal_newlines=True)
print("nvcc version is : " + raw_output)
```
The output of my computer is:

> torch version is: 2.4.0+**cu124**
> CUDA HOME is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v12.5
> nvcc version is : nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2024 NVIDIA Corporation
> Built on Wed_Apr_17_19:36:51_Pacific_Daylight_Time_2024
> Cuda compilation tools, release 12.5, V12.5.40
> Build cuda_12.5.r12.5/compiler.34177558_0

Could you show me what the output is on your computer?

**Comment by whisper-bye** [comment]
torch version is: 2.4.0+cpu
CUDA HOME is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6
nvcc version is : nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Fri_Jun_14_16:44:19_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.6, V12.6.20
Build cuda_12.6.r12.6/compiler.34431801_0

thanks for your quick reply, after fixup some torch things ...

```
python -m ktransformers.local_chat --model_name Qwen/Qwen2-57B-A14B-Instruct --gguf_path ./Qwen2-57B-GGUF
ERROR: The function received no value for the required argument: model_path
Usage: local_chat.py MODEL_PATH <flags>
  optional flags:        --optimize_rule_path | --gguf_path |
                         --max_new_tokens | --cpu_infer

For detailed information on this command, run:
  local_chat.py --help
```

**Comment by UnicornChan** [comment]
> torch version is: 2.4.0+cpu CUDA HOME is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6 nvcc version is : nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2024 NVIDIA Corporation Built on Fri_Jun_14_16:44:19_Pacific_Daylight_Time_2024 Cuda compilation tools, release 12.6, V12.6.20 Build cuda_12.6.r12.6/compiler.34431801_0
> 
> thanks for your quick reply, after fixup some torch things ...
> 
> ```
> python -m ktransformers.local_chat --model_name Qwen/Qwen2-57B-A14B-Instruct --gguf_path ./Qwen2-57B-GGUF
> ERROR: The function received no value for the required argument: model_path
> Usage: local_chat.py MODEL_PATH <flags>
>   optional flags:        --optimize_rule_path | --gguf_path |
>                          --max_new_tokens | --cpu_infer
> 
> For detailed information on this command, run:
>   local_chat.py --help
> ```

Perhaps you should input --model_path instead of --model_name.
```
python -m ktransformers.local_chat --model_path Qwen/Qwen2-57B-A14B-Instruct --gguf_path ./Qwen2-57B-GGUF
```

**Comment by whisper-bye** [comment]
Great, it works!
```
Chat: 数字9.11和9.9谁大？ 
数字9.11和9.9中，9.11比9.9小。这可以通过将两个数字转换为分数来更清楚地看到，其中9.11为911/1000和9.9为99/10。比较两个分数，911/1000小于99/10，因此9.11小于9.9。
prompt eval count:    31 token(s)
prompt eval duration: 0.757000207901001s
prompt eval rate:     40.95111160663528 tokens/s
eval count:           90 token(s)
eval duration:        6.651063442230225s
eval rate:            13.531670654132467 tokens/s
```
