### ISSUE TITLE
How to properly disable offloading MoE layers to CPU?

### ISSUE THREAD

**Issue by molamooo** [kvcache-ai/ktransformers#50]

**Comment by Azure-Tang** [comment]
Regarding your question on disabling the offloading of MoE layers to the CPU, I’ve provided a brief explanation in my earlier response (#46 ). Please take a look there for detailed instructions.

**Comment by molamooo** [comment]
I tried using custom rule file to put all layers on GPU, but KTransformer triggers oom when dequantizing parameters. I use a 24GB 4090 to run deepseek-v2-lite-chat with q8_0 quantization. It should only takes ~16GB memory. Other systems like llama.cpp can run without issue.

**Comment by ELigoP** [comment]
This is hardly possible.
What is your model size? With q8 quantization it should be >200 GB. If you

> put all layers on GPU

no wonder it OOMs. Llama.cpp automatically offloads layers in to CPU suboptimal way. If you force it to offload everything to GPU it will also OOM.

E.g. with my setup I get 7.5 tps with suboptimal llama.cpp CPU offload and 9 tps with ktransformers (even that it utilizies VRAM suboptimally).

**Comment by molamooo** [comment]
> This is hardly possible. What is your model size? With q8 quantization it should be >200 GB. If you
I mentioned that I use deepseek-v2-lite-chat, which is a 16B model. It shouldn't oom.

**Comment by Azure-Tang** [comment]
I see, if you are using KExpertsTorch as backend, it will dequant the weights to model's default dtype, for deepseek this is bf16. So this is why it oom. Maybe you can try marlin backend? But we didn't optimise this operator in generate phase.
