### ISSUE TITLE
Support for Mistral-Large-Instruct-2407-GGUF ？

### ISSUE THREAD

**Issue by LIUKAI0815** [kvcache-ai/ktransformers#53]
Q2、Q3、Q4、Q8、BF16、FP16 ？

**Comment by BITcyman** [comment]
Currently, ktransformers mainly focus on speeding up MoE models. So we support Mixtral-8x7b and Mixtral-8x22b in Release v0.1.2. But Mistral-Large-Instruct is a dense model, which we might not support in the near future.

**Comment by LIUKAI0815** [comment]
@BITcyman Thanks for replying and looking forward to the new release.

**Comment by RWayne93** [comment]
I know this is closed but what about large 3 mistralai/Mistral-Large-3-675B-Instruct-2512 this is a MOE model.
