### ISSUE TITLE
Could you provide a Docker image?

### ISSUE THREAD

**Issue by goldenquant** [kvcache-ai/ktransformers#9]
Could you provide a Docker image?

**Comment by james0zan** [comment]
We will provide pip install support in these two days and then the dockerfile

**Comment by UnicornChan** [comment]
> Could you provide a Docker image?

We have provided an image on DockerHub, which can be pulled using ```docker pull approachingai/ktransformers:0.1.1```. Using can be found on the [Docker.md](https://github.com/kvcache-ai/ktransformers/blob/main/doc/en/Docker.md). We look forward to your feedback.
