### ISSUE TITLE
Deepseekv2推理速度很慢，看样子似乎在cpu上做推理，gpu利用率很低

### ISSUE THREAD

**Issue by Chain-Mao** [kvcache-ai/ktransformers#93]
<img width="1025" alt="截屏2024-09-19 23 32 12" src="https://github.com/user-attachments/assets/eb1b5484-ec60-4cf9-b203-99d4b7cdc7c8">
我是在local_chat.py基础上修改成了批量推理，模型放在gpu上，但似乎推理是在cpu上进行的。请问大佬知道如何解决嘛

**Comment by Azure-Tang** [comment]
所有模块都是放在gpu上的么？可以分享一下您的代码/yaml规则文件。我们目前没有对batch做过优化，所以默认的配置下跑batch确实可能会慢一些。

**Comment by Chain-Mao** [comment]
> 所有模块都是放在gpu上的么？可以分享一下您的代码/yaml规则文件。我们目前没有对batch做过优化，所以默认的配置下跑batch确实可能会慢一些。

貌似锁定原因了，是我的RAM不足。这个不会导致程序报错但似乎会大大影响推理速度。

**Comment by Azure-Tang** [comment]
是这样的～
