### ISSUE TITLE
Suggestion to add DeepSeek v2.5 support

### ISSUE THREAD

**Issue by arisau** [kvcache-ai/ktransformers#95]
Recently DeepSeek 2.5 MoE model was released. Please consider adding a support for it. (Q5_K_M or Q4_K_M)

**Comment by Azure-Tang** [comment]
It appears to be supported automatically, as some users have already tested it successfully.

**Comment by arisau** [comment]
Perfect. Thank you. 
just to confirm, only Q4_K_M works?

**Comment by Azure-Tang** [comment]
We have supported all Qx
_km format~

**Comment by arisau** [comment]
Understood. Thank you once again.
